export const classColorList = {
  Paladin: "#F48CBA",
  Druid: "#FF7C0A",
  Evoker: "#33937F",
  Hunter: "#AAD372",
  Mage: "#3FC7EB",
  Monk: "#00FF98",
  Priest: "#FFFFFF",
  Rogue: "#FFF468",
  Shaman: "#0070DD",
  Warlock: "#8788EE",
  Warrior: "#C69B6D",
  "Demon Hunter": "#A330C9",
  "Death Knight": "#C41E3A",
};

export const euServerList = [
  { name: "Aerie Peak", slugName: "aerie-peak" },
  { name: "Agamaggan", slugName: "agamaggan" },
  { name: "Aggra (Português)", slugName: "aggra-português" },
  { name: "Aggramar", slugName: "aggramar" },
  { name: "Ahn'Qiraj", slugName: "ahnqiraj" },
  { name: "Al'Akir", slugName: "alakir" },
  { name: "Alonsus", slugName: "alonsus" },
  { name: "Anachronos", slugName: "anachronos" },
  { name: "Arathor", slugName: "arathor" },
  { name: "Argent Dawn", slugName: "argent-dawn" },
  { name: "Aszune", slugName: "aszune" },
  { name: "Auchindoun", slugName: "auchindoun" },
  { name: "Azjol-Nerub", slugName: "azjolnerub" },
  { name: "Azuremyst", slugName: "azuremyst" },
  { name: "Balnazzar", slugName: "balnazzar" },
  { name: "Blade's Edge", slugName: "blades-edge" },
  { name: "Bladefist", slugName: "bladefist" },
  { name: "Bloodfeather", slugName: "bloodfeather" },
  { name: "Bloodhoof", slugName: "bloodhoof" },
  { name: "Bloodscalp", slugName: "bloodscalp" },
  { name: "Boulderfist", slugName: "boulderfist" },
  { name: "Bronze Dragonflight", slugName: "bronze-dragonflight" },
  { name: "Bronzebeard", slugName: "bronzebeard" },
  { name: "Burning Blade", slugName: "burning-blade" },
  { name: "Burning Legion", slugName: "burning-legion" },
  { name: "Burning Steppes", slugName: "burning-steppes" },
  { name: "Chamber of Aspects", slugName: "chamber-of-aspects" },
  { name: "Chromaggus", slugName: "chromaggus" },
  { name: "Crushridge", slugName: "crushridge" },
  { name: "Daggerspine", slugName: "daggerspine" },
  { name: "Darkmoon Faire", slugName: "darkmoon-faire" },
  { name: "Darksorrow", slugName: "darksorrow" },
  { name: "Darkspear", slugName: "darkspear" },
  { name: "Deathwing", slugName: "deathwing" },
  { name: "Defias Brotherhood", slugName: "defias-brotherhood" },
  { name: "Dentarg", slugName: "dentarg" },
  { name: "Doomhammer", slugName: "doomhammer" },
  { name: "Draenor", slugName: "draenor" },
  { name: "Dragonblight", slugName: "dragonblight" },
  { name: "Dragonmaw", slugName: "dragonmaw" },
  { name: "Drak'thul", slugName: "drakthul" },
  { name: "Dunemaul", slugName: "dunemaul" },
  { name: "Earthen Ring", slugName: "earthen-ring" },
  { name: "Emerald Dream", slugName: "emerald-dream" },
  { name: "Emeriss", slugName: "emeriss" },
  { name: "Eonar", slugName: "eonar" },
  { name: "Executus", slugName: "executus" },
  { name: "Frostmane", slugName: "frostmane" },
  { name: "Frostwhisper", slugName: "frostwhisper" },
  { name: "Genjuros", slugName: "genjuros" },
  { name: "Ghostlands", slugName: "ghostlands" },
  { name: "Grim Batol", slugName: "grim-batol" },
  { name: "Hakkar", slugName: "hakkar" },
  { name: "Haomarush", slugName: "haomarush" },
  { name: "Hellfire", slugName: "hellfire" },
  { name: "Hellscream", slugName: "hellscream" },
  { name: "Jaedenar", slugName: "jaedenar" },
  { name: "Karazhan", slugName: "karazhan" },
  { name: "Kazzak", slugName: "kazzak" },
  { name: "Khadgar", slugName: "khadgar" },
  { name: "Kilrogg", slugName: "kilrogg" },
  { name: "Kor'gall", slugName: "korgall" },
  { name: "Kul Tiras", slugName: "kul-tiras" },
  { name: "Laughing Skull", slugName: "laughing-skull" },
  { name: "Lightbringer", slugName: "lightbringer" },
  { name: "Lightning's Blade", slugName: "lightnings-blade" },
  { name: "Magtheridon", slugName: "magtheridon" },
  { name: "Mazrigos", slugName: "mazrigos" },
  { name: "Moonglade", slugName: "moonglade" },
  { name: "Nagrand", slugName: "nagrand" },
  { name: "Neptulon", slugName: "neptulon" },
  { name: "Nordrassil", slugName: "nordrassil" },
  { name: "Outland", slugName: "outland" },
  { name: "Quel'Thalas", slugName: "quelthalas" },
  { name: "Ragnaros", slugName: "ragnaros" },
  { name: "Ravencrest", slugName: "ravencrest" },
  { name: "Ravenholdt", slugName: "ravenholdt" },
  { name: "Runetotem", slugName: "runetotem" },
  { name: "Saurfang", slugName: "saurfang" },
  { name: "Scarshield Legion", slugName: "scarshield-legion" },
  { name: "Shadowsong", slugName: "shadowsong" },
  { name: "Shattered Halls", slugName: "shattered-halls" },
  { name: "Shattered Hand", slugName: "shattered-hand" },
  { name: "Silvermoon", slugName: "silvermoon" },
  { name: "Skullcrusher", slugName: "skullcrusher" },
  { name: "Spinebreaker", slugName: "spinebreaker" },
  { name: "Sporeggar", slugName: "sporeggar" },
  { name: "Steamwheedle Cartel", slugName: "steamwheedle-cartel" },
  { name: "Stormrage", slugName: "stormrage" },
  { name: "Stormreaver", slugName: "stormreaver" },
  { name: "Stormscale", slugName: "stormscale" },
  { name: "Sunstrider", slugName: "sunstrider" },
  { name: "Sylvanas", slugName: "sylvanas" },
  { name: "Talnivarr", slugName: "talnivarr" },
  { name: "Tarren Mill", slugName: "tarren-mill" },
  { name: "Terenas", slugName: "terenas" },
  { name: "Terokkar", slugName: "terokkar" },
  { name: "The Maelstrom", slugName: "the-maelstrom" },
  { name: "The Sha'tar", slugName: "the-shatar" },
  { name: "The Venture Co", slugName: "the-venture-co" },
  { name: "Thunderhorn", slugName: "thunderhorn" },
  { name: "Trollbane", slugName: "trollbane" },
  { name: "Turalyon", slugName: "turalyon" },
  { name: "Twilight's Hammer", slugName: "twilights-hammer" },
  { name: "Twisting Nether", slugName: "twisting-nether" },
  { name: "Vashj", slugName: "vashj" },
  { name: "Vek'nilash", slugName: "veknilash" },
  { name: "Wildhammer", slugName: "wildhammer" },
  { name: "Xavius", slugName: "xavius" },
  { name: "Zenedar", slugName: "zenedar" },
];
