export const classColorList = {
  Paladin: "#F48CBA",
  Druid: "#FF7C0A",
  Evoker: "#33937F",
  Hunter: "#AAD372",
  Mage: "#3FC7EB",
  Monk: "#00FF98",
  Priest: "#FFFFFF",
  Rogue: "#FFF468",
  Shaman: "#0070DD",
  Warlock: "#8788EE",
  Warrior: "#C69B6D",
  "Demon Hunter": "#A330C9",
  "Death Knight": "#C41E3A",
};

export const euServerList = [
  { name: "Aerie Peak", slugName: "aerie-peak" },
  { name: "Agamaggan", slugName: "agamaggan" },
  { name: "Aggra (Português)", slugName: "aggra-português" },
  { name: "Aggramar", slugName: "aggramar" },
  { name: "Ahn'Qiraj", slugName: "ahnqiraj" },
  { name: "Al'Akir", slugName: "alakir" },
  { name: "Alonsus", slugName: "alonsus" },
  { name: "Anachronos", slugName: "anachronos" },
  { name: "Arathor", slugName: "arathor" },
  { name: "Argent Dawn", slugName: "argent-dawn" },
  { name: "Aszune", slugName: "aszune" },
  { name: "Auchindoun", slugName: "auchindoun" },
  { name: "Azjol-Nerub", slugName: "azjolnerub" },
  { name: "Azuremyst", slugName: "azuremyst" },
  { name: "Balnazzar", slugName: "balnazzar" },
  { name: "Blade's Edge", slugName: "blades-edge" },
  { name: "Bladefist", slugName: "bladefist" },
  { name: "Bloodfeather", slugName: "bloodfeather" },
  { name: "Bloodhoof", slugName: "bloodhoof" },
  { name: "Bloodscalp", slugName: "bloodscalp" },
  { name: "Boulderfist", slugName: "boulderfist" },
  { name: "Bronze Dragonflight", slugName: "bronze-dragonflight" },
  { name: "Bronzebeard", slugName: "bronzebeard" },
  { name: "Burning Blade", slugName: "burning-blade" },
  { name: "Burning Legion", slugName: "burning-legion" },
  { name: "Burning Steppes", slugName: "burning-steppes" },
  { name: "Chamber of Aspects", slugName: "chamber-of-aspects" },
  { name: "Chromaggus", slugName: "chromaggus" },
  { name: "Crushridge", slugName: "crushridge" },
  { name: "Daggerspine", slugName: "daggerspine" },
  { name: "Darkmoon Faire", slugName: "darkmoon-faire" },
  { name: "Darksorrow", slugName: "darksorrow" },
  { name: "Darkspear", slugName: "darkspear" },
  { name: "Deathwing", slugName: "deathwing" },
  { name: "Defias Brotherhood", slugName: "defias-brotherhood" },
  { name: "Dentarg", slugName: "dentarg" },
  { name: "Doomhammer", slugName: "doomhammer" },
  { name: "Draenor", slugName: "draenor" },
  { name: "Dragonblight", slugName: "dragonblight" },
  { name: "Dragonmaw", slugName: "dragonmaw" },
  { name: "Drak'thul", slugName: "drakthul" },
  { name: "Dunemaul", slugName: "dunemaul" },
  { name: "Earthen Ring", slugName: "earthen-ring" },
  { name: "Emerald Dream", slugName: "emerald-dream" },
  { name: "Emeriss", slugName: "emeriss" },
  { name: "Eonar", slugName: "eonar" },
  { name: "Executus", slugName: "executus" },
  { name: "Frostmane", slugName: "frostmane" },
  { name: "Frostwhisper", slugName: "frostwhisper" },
  { name: "Genjuros", slugName: "genjuros" },
  { name: "Ghostlands", slugName: "ghostlands" },
  { name: "Grim Batol", slugName: "grim-batol" },
  { name: "Hakkar", slugName: "hakkar" },
  { name: "Haomarush", slugName: "haomarush" },
  { name: "Hellfire", slugName: "hellfire" },
  { name: "Hellscream", slugName: "hellscream" },
  { name: "Jaedenar", slugName: "jaedenar" },
  { name: "Karazhan", slugName: "karazhan" },
  { name: "Kazzak", slugName: "kazzak" },
  { name: "Khadgar", slugName: "khadgar" },
  { name: "Kilrogg", slugName: "kilrogg" },
  { name: "Kor'gall", slugName: "korgall" },
  { name: "Kul Tiras", slugName: "kul-tiras" },
  { name: "Laughing Skull", slugName: "laughing-skull" },
  { name: "Lightbringer", slugName: "lightbringer" },
  { name: "Lightning's Blade", slugName: "lightnings-blade" },
  { name: "Magtheridon", slugName: "magtheridon" },
  { name: "Mazrigos", slugName: "mazrigos" },
  { name: "Moonglade", slugName: "moonglade" },
  { name: "Nagrand", slugName: "nagrand" },
  { name: "Neptulon", slugName: "neptulon" },
  { name: "Nordrassil", slugName: "nordrassil" },
  { name: "Outland", slugName: "outland" },
  { name: "Quel'Thalas", slugName: "quelthalas" },
  { name: "Ragnaros", slugName: "ragnaros" },
  { name: "Ravencrest", slugName: "ravencrest" },
  { name: "Ravenholdt", slugName: "ravenholdt" },
  { name: "Runetotem", slugName: "runetotem" },
  { name: "Saurfang", slugName: "saurfang" },
  { name: "Scarshield Legion", slugName: "scarshield-legion" },
  { name: "Shadowsong", slugName: "shadowsong" },
  { name: "Shattered Halls", slugName: "shattered-halls" },
  { name: "Shattered Hand", slugName: "shattered-hand" },
  { name: "Silvermoon", slugName: "silvermoon" },
  { name: "Skullcrusher", slugName: "skullcrusher" },
  { name: "Spinebreaker", slugName: "spinebreaker" },
  { name: "Sporeggar", slugName: "sporeggar" },
  { name: "Steamwheedle Cartel", slugName: "steamwheedle-cartel" },
  { name: "Stormrage", slugName: "stormrage" },
  { name: "Stormreaver", slugName: "stormreaver" },
  { name: "Stormscale", slugName: "stormscale" },
  { name: "Sunstrider", slugName: "sunstrider" },
  { name: "Sylvanas", slugName: "sylvanas" },
  { name: "Talnivarr", slugName: "talnivarr" },
  { name: "Tarren Mill", slugName: "tarren-mill" },
  { name: "Terenas", slugName: "terenas" },
  { name: "Terokkar", slugName: "terokkar" },
  { name: "The Maelstrom", slugName: "the-maelstrom" },
  { name: "The Sha'tar", slugName: "the-shatar" },
  { name: "The Venture Co", slugName: "the-venture-co" },
  { name: "Thunderhorn", slugName: "thunderhorn" },
  { name: "Trollbane", slugName: "trollbane" },
  { name: "Turalyon", slugName: "turalyon" },
  { name: "Twilight's Hammer", slugName: "twilights-hammer" },
  { name: "Twisting Nether", slugName: "twisting-nether" },
  { name: "Vashj", slugName: "vashj" },
  { name: "Vek'nilash", slugName: "veknilash" },
  { name: "Wildhammer", slugName: "wildhammer" },
  { name: "Xavius", slugName: "xavius" },
  { name: "Zenedar", slugName: "zenedar" },
];

export const usServerList = [
  { name: "Area 52", slugName: "area-52" },
  { name: "Stormrage", slugName: "stormrage" },
  { name: "Illidan", slugName: "illidan" },
  { name: "Tichondrius", slugName: "tichondrius" },
  { name: "Dreadmaul", slugName: "dreadmaul" },
  { name: "Frostmourne", slugName: "frostmourne" },
  { name: "Gundrak", slugName: "gundrak" },
  { name: "Jubei'Thos", slugName: "jubei-thos" },
  { name: "Thaurissan", slugName: "thaurissan" },
  { name: "Sargeras", slugName: "sargeras" },
  { name: "Thrall", slugName: "thrall" },
  { name: "Zul'jin", slugName: "zuljin" },
  { name: "Moon Guard", slugName: "moon-guard" },
  { name: "Proudmoore", slugName: "proudmoore" },
  { name: "Ragnaros", slugName: "ragnaros" },
  { name: "Azralon", slugName: "azralon" },
  { name: "Mal'Ganis", slugName: "malganis" },
  { name: "Quel'Thalas", slugName: "quelthalas" },
  { name: "Dalaran", slugName: "dalaran" },
  { name: "Aegwynn", slugName: "aegwynn" },
  { name: "Bonechewer", slugName: "bonechewer" },
  { name: "Daggerspine", slugName: "daggerspine" },
  { name: "Garrosh", slugName: "garrosh" },
  { name: "Gurubashi", slugName: "gurubashi" },
  { name: "Hakkar", slugName: "hakkar" },
  { name: "Azgalor", slugName: "azgalor" },
  { name: "Azshara", slugName: "azshara" },
  { name: "Blood Furnace", slugName: "blood-furnace" },
  { name: "Destromath", slugName: "destromath" },
  { name: "Mannoroth", slugName: "mannoroth" },
  { name: "Nazjatar", slugName: "nazjatar" },
  { name: "Thunderlord", slugName: "thunderlord" },
  { name: "Wyrmrest Accord", slugName: "wyrmrest-accord" },
  { name: "Ghostlands", slugName: "ghostlands" },
  { name: "Gnomeregan", slugName: "gnomeregan" },
  { name: "Grizzly Hills", slugName: "grizzly-hills" },
  { name: "Kael'thas", slugName: "kaelthas" },
  { name: "Lothar", slugName: "lothar" },
  { name: "Malfurion", slugName: "malfurion" },
  { name: "Moonrunner", slugName: "moonrunner" },
  { name: "Trollbane", slugName: "trollbane" },
  { name: "Bleeding Hollow", slugName: "bleeding-hollow" },
  { name: "Borean Tundra", slugName: "borean-tundra" },
  { name: "Drak'thul", slugName: "drakthul" },
  { name: "Hydraxis", slugName: "hydraxis" },
  { name: "Mok'Nathal", slugName: "moknathal" },
  { name: "Shadowsong", slugName: "shadowsong" },
  { name: "Silvermoon", slugName: "silvermoon" },
  { name: "Skywall", slugName: "skywall" },
  { name: "Terenas", slugName: "terenas" },
  { name: "Barthilas", slugName: "barthilas" },
  { name: "Agamaggan", slugName: "agamaggan" },
  { name: "Archimonde", slugName: "archimonde" },
  { name: "Blade's Edge", slugName: "blades-edge" },
  { name: "Burning Legion", slugName: "burning-legion" },
  { name: "Jaedenar", slugName: "jaedenar" },
  { name: "Kargath", slugName: "kargath" },
  { name: "Norgannon", slugName: "norgannon" },
  { name: "The Underbog", slugName: "the-underbog" },
  { name: "Thunderhorn", slugName: "thunderhorn" },
  { name: "Emerald Dream", slugName: "emerald-dream" },
  { name: "Cairne", slugName: "cairne" },
  { name: "Cenarius", slugName: "cenarius" },
  { name: "Frostmane", slugName: "frostmane" },
  { name: "Korgath", slugName: "korgath" },
  { name: "Ner'zhul", slugName: "nerzhul" },
  { name: "Perenolde", slugName: "perenolde" },
  { name: "Tortheldrin", slugName: "tortheldrin" },
  { name: "Burning Blade", slugName: "burning-blade" },
  { name: "Garona", slugName: "garona" },
  { name: "Icecrown", slugName: "icecrown" },
  { name: "Lightning's Blade", slugName: "lightnings-blade" },
  { name: "Malygos", slugName: "malygos" },
  { name: "Onyxia", slugName: "onyxia" },
  { name: "Caelestrasz", slugName: "caelestrasz" },
  { name: "Nagrand", slugName: "nagrand" },
  { name: "Saurfang", slugName: "saurfang" },
  { name: "Akama", slugName: "akama" },
  { name: "Antonidas", slugName: "antonidas" },
  { name: "Dragonmaw", slugName: "dragonmaw" },
  { name: "Eldre'Thalas", slugName: "eldrethalas" },
  { name: "Korialstrasz", slugName: "korialstrasz" },
  { name: "Mug'thol", slugName: "mugthol" },
  { name: "Uldum", slugName: "uldum" },
  { name: "Kel'Thuzad", slugName: "kelthuzad" },
  { name: "Aman'Thul", slugName: "amanthul" },
  { name: "Dath'Remar", slugName: "dathremar" },
  { name: "Khaz'goroth", slugName: "khazgoroth" },
  { name: "Andorhal", slugName: "andorhal" },
  { name: "Black Dragonflight", slugName: "black-dragonflight" },
  { name: "Eonar", slugName: "eonar" },
  { name: "Gul'dan", slugName: "guldan" },
  { name: "Scilla", slugName: "scilla" },
  { name: "Skullcrusher", slugName: "skullcrusher" },
  { name: "Ursin", slugName: "ursin" },
  { name: "Velen", slugName: "velen" },
  { name: "Zuluhed", slugName: "zuluhed" },
  { name: "Azjol-Nerub", slugName: "azjol-nerub" },
  { name: "Blackrock", slugName: "blackrock" },
  { name: "Khaz Modan", slugName: "khaz-modan" },
  { name: "Muradin", slugName: "muradin" },
  { name: "Nordrassil", slugName: "nordrassil" },
  { name: "Bloodscalp", slugName: "bloodscalp" },
  { name: "Boulderfist", slugName: "boulderfist" },
  { name: "Dunemaul", slugName: "dunemaul" },
  { name: "Maiev", slugName: "maiev" },
  { name: "Quel'dorei", slugName: "queldorei" },
  { name: "Sen'jin", slugName: "senjin" },
  { name: "Stonemaul", slugName: "stonemaul" },
  { name: "Drak'Tharon", slugName: "draktharon" },
  { name: "Firetree", slugName: "firetree" },
  { name: "Frostwolf", slugName: "frostwolf" },
  { name: "Malorne", slugName: "malorne" },
  { name: "Rivendare", slugName: "rivendare" },
  { name: "Spirestone", slugName: "spirestone" },
  { name: "Stormscale", slugName: "stormscale" },
  { name: "Vashj", slugName: "vashj" },
  { name: "Hyjal", slugName: "hyjal" },
  { name: "Alleria", slugName: "alleria" },
  { name: "Exodar", slugName: "exodar" },
  { name: "Khadgar", slugName: "khadgar" },
  { name: "Medivh", slugName: "medivh" },
  { name: "Eredar", slugName: "eredar" },
  { name: "Gorefiend", slugName: "gorefiend" },
  { name: "Hellscream", slugName: "hellscream" },
  { name: "Spinebreaker", slugName: "spinebreaker" },
  { name: "Wildhammer", slugName: "wildhammer" },
  { name: "Zangarmarsh", slugName: "zangarmarsh" },
  { name: "Auchindoun", slugName: "auchindoun" },
  { name: "Cho'gall", slugName: "chogall" },
  { name: "Elune", slugName: "elune" },
  { name: "Gilneas", slugName: "gilneas" },
  { name: "Laughing Skull", slugName: "laughing-skull" },
  { name: "Kil'jaeden", slugName: "kiljaeden" },
  { name: "Darrowmere", slugName: "darrowmere" },
  { name: "Draka", slugName: "draka" },
  { name: "Suramar", slugName: "suramar" },
  { name: "Windrunner", slugName: "windrunner" },
  { name: "Azuremyst", slugName: "azuremyst" },
  { name: "Dawnbringer", slugName: "dawnbringer" },
  { name: "Madoran", slugName: "madoran" },
  { name: "Staghelm", slugName: "staghelm" },
  { name: "Anub'arak", slugName: "anubarak" },
  { name: "Arathor", slugName: "arathor" },
  { name: "Chromaggus", slugName: "chromaggus" },
  { name: "Crushridge", slugName: "crushridge" },
  { name: "Drenden", slugName: "drenden" },
  { name: "Garithos", slugName: "garithos" },
  { name: "Nathrezim", slugName: "nathrezim" },
  { name: "Smolderthorn", slugName: "smolderthorn" },
  { name: "Lightbringer", slugName: "lightbringer" },
  { name: "Blackwater Raiders", slugName: "blackwater-raiders" },
  { name: "Cenarion Circle", slugName: "cenarion-circle" },
  { name: "Shadow Council", slugName: "shadow-council" },
  { name: "Sisters of Elune", slugName: "sisters-of-elune" },
  { name: "Dentarg", slugName: "dentarg" },
  { name: "Whisperwind", slugName: "whisperwind" },
  { name: "Alterac Mountains", slugName: "alterac-mountains" },
  { name: "Anvilmar", slugName: "anvilmar" },
  { name: "Balnazzar", slugName: "balnazzar" },
  { name: "Gorgonnash", slugName: "gorgonnash" },
  { name: "The Forgotten Coast", slugName: "the-forgotten-coast" },
  { name: "Undermine", slugName: "undermine" },
  { name: "Warsong", slugName: "warsong" },
  { name: "Aggramar", slugName: "aggramar" },
  { name: "Fizzcrank", slugName: "fizzcrank" },
  { name: "Aerie Peak", slugName: "aerie-peak" },
  { name: "Nemesis", slugName: "nemesis" },
  { name: "Tol Barad", slugName: "tol-barad" },
  { name: "Drakkari", slugName: "drakkari" },
  { name: "Farstriders", slugName: "farstriders" },
  { name: "Silver Hand", slugName: "silver-hand" },
  { name: "Thorium Brotherhood", slugName: "thorium-brotherhood" },
  { name: "Durotan", slugName: "durotan" },
  { name: "Ysera", slugName: "ysera" },
  { name: "Lightninghoof", slugName: "lightninghoof" },
  { name: "Maelstrom", slugName: "maelstrom" },
  { name: "Ravenholdt", slugName: "ravenholdt" },
  { name: "The Venture Co", slugName: "the-venture-co" },
  { name: "Twisting Nether", slugName: "twisting-nether" },
  { name: "Bloodhoof", slugName: "bloodhoof" },
  { name: "Duskwood", slugName: "duskwood" },
  { name: "Arthas", slugName: "arthas" },
  { name: "Baelgun", slugName: "baelgun" },
  { name: "Doomhammer", slugName: "doomhammer" },
  { name: "Alexstrasza", slugName: "alexstrasza" },
  { name: "Terokkar", slugName: "terokkar" },
  { name: "Nazgrel", slugName: "nazgrel" },
  { name: "Nesingwary", slugName: "nesingwary" },
  { name: "Vek'nilash", slugName: "veknilash" },
  { name: "Blackhand", slugName: "blackhand" },
  { name: "Galakrond", slugName: "galakrond" },
  { name: "Feathermoon", slugName: "feathermoon" },
  { name: "Scarlet Crusade", slugName: "scarlet-crusade" },
  { name: "Greymane", slugName: "greymane" },
  { name: "Tanaris", slugName: "tanaris" },
  { name: "Argent Dawn", slugName: "argent-dawn" },
  { name: "The Scryers", slugName: "the-scryers" },
  { name: "Draenor", slugName: "draenor" },
  { name: "Echo Isles", slugName: "echo-isles" },
  { name: "Turalyon", slugName: "turalyon" },
  { name: "Altar of Storms", slugName: "altar-of-storms" },
  { name: "Anetheron", slugName: "anetheron" },
  { name: "Magtheridon", slugName: "magtheridon" },
  { name: "Ysondre", slugName: "ysondre" },
  { name: "Kirin Tor", slugName: "kirin-tor" },
  { name: "Sentinels", slugName: "sentinels" },
  { name: "Steamwheedle Cartel", slugName: "steamwheedle-cartel" },
  { name: "Runetotem", slugName: "runetotem" },
  { name: "Uther", slugName: "uther" },
  { name: "Ravencrest", slugName: "ravencrest" },
  { name: "Uldaman", slugName: "uldaman" },
  { name: "Misha", slugName: "misha" },
  { name: "Rexxar", slugName: "rexxar" },
  { name: "Bladefist", slugName: "bladefist" },
  { name: "Kul Tiras", slugName: "kul-tiras" },
  { name: "Darkspear", slugName: "darkspear" },
  { name: "Deathwing", slugName: "deathwing" },
  { name: "Executus", slugName: "executus" },
  { name: "Kalecgos", slugName: "kalecgos" },
  { name: "Shattered Halls", slugName: "shattered-halls" },
  { name: "Eitrigg", slugName: "eitrigg" },
  { name: "Shu'halo", slugName: "shuhalo" },
  { name: "Arygos", slugName: "arygos" },
  { name: "Llane", slugName: "llane" },
  { name: "Kilrogg", slugName: "kilrogg" },
  { name: "Winterhoof", slugName: "winterhoof" },
  { name: "Dragonblight", slugName: "dragonblight" },
  { name: "Fenris", slugName: "fenris" },
  { name: "Coilfang", slugName: "coilfang" },
  { name: "Dalvengyr", slugName: "dalvengyr" },
  { name: "Dark Iron", slugName: "dark-iron" },
  { name: "Demon Soul", slugName: "demon-soul" },
  { name: "Shattered Hand", slugName: "shattered-hand" },
  { name: "Blackwing Lair", slugName: "blackwing-lair" },
  { name: "Dethecus", slugName: "dethecus" },
  { name: "Detheroc", slugName: "detheroc" },
  { name: "Haomarush", slugName: "haomarush" },
  { name: "Lethon", slugName: "lethon" },
  { name: "Shadowmoon", slugName: "shadowmoon" },
  { name: "Bronzebeard", slugName: "bronzebeard" },
  { name: "Shandris", slugName: "shandris" },
  { name: "Earthen Ring", slugName: "earthen-ring" },
  { name: "Stormreaver", slugName: "stormreaver" },
  { name: "Goldrinn", slugName: "goldrinn" },
  { name: "Gallywix", slugName: "gallywix" },
];
